language: android
android:
  components:
  - platform-tools
  - tools
  - android-19
  - sys-img-armeabi-v7a-android-19
env:
  - DISPLAY=:99.0
  - JPM_ADB_PATH=/usr/local/android-sdk/platform-tools/adb
  - JPM_FIREFOX_BINARY=fennec
  - TMP_DIR=/tmp
before_install:
- sh -e /etc/init.d/xvfb start
- mkdir -p $TMP_DIR/sdcard
- mksdcard -l jetpackSdCard 1024M $TMP_DIR/sdcard/jpmsdcard.img
- rm -f $TMP_DIR/sdcard/jpmsdcard.img.lock
- echo no | android create avd --force -n jpm -t android-19 --abi armeabi-v7a
- emulator -avd jpm -sdcard $TMP_DIR/sdcard/jpmsdcard.img -no-audio -gpu off -no-boot-anim -noskin &
- android-wait-for-emulator
before_script:
- npm install -g get-firefox
- git clone --depth 1 -b fixes https://github.com/ncalexan/jpm-mobile.git $TMP_DIR/jpm-mobile
- cd $TMP_DIR/jpm-mobile
- npm link
- cd $TRAVIS_BUILD_DIR
- get-firefox -c -p android -t $TMP_DIR/fennec.apk
- adb wait-for-device
- adb emu input keyevent 82 &
- adb install $TMP_DIR/fennec.apk
script:
- jpm-mobile test -v --adb $JPM_ADB_PATH -b $JPM_FIREFOX_BINARY
deploy:
  provider: npm
  email: martin@humanoids.be
  on:
    tags: true
  api_key:
    secure: DNgnzqrmCBaER+yEvGCAeRJLL9BeBjfvZC/K+gos/QUzQ6S/EaDjSGRJGBxarW0k5EbGL9LkrgBy3M3nXzHsLCDcS4ewvzKL4X6jH2qfIPvQc6fLu/lKy9yBrRfyaiG8fKVR+3Vm7YlZ940OCtiLkEf1Z+ezPY5TJdjKJEmjv2Q=
