language: android
android:
  components:
    - platform-tools
    - tools

    # The SDK version used to compile your project
    - android-17

    # Specify system image,
    - sys-img-armea

# Emulator Management: Create, Start and Wait
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Go to playground
  - cd /tmp
  # Make a fake sd card
  - mkdir sdcard
  - mksdcard -l jetpackSdCard 1024M sdcard/jetpacksdcard.img
  # Create the emulator
  - echo no | android create avd --force -n jetpack -t android-17 --abi armeabi-v7a
  # Start the emulator
  - emulator -avd jetpack -sdcard sdcard/jetpacksdcard.img -no-audio -gpu on -no-boot-anim -noskin &
  # Wait for the emulator to start
  - android-wait-for-emulator
  # Unlock the emulator
  - adb shell input keyevent 82 &
  - adb shell input keyevent 82 &
  # Download Nightly
  - wget -O fennec.apk https://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-central-android-api-11/fennec-40.0a1.multi.android-arm.apk
  # Install Nightly
  - adb install fennec.apk
  # Go back to real business
  - cd $TRAVIS_BUILD_DIR
  # Install dependencies
  - npm install jpm-mobile -g
  - export JPM_FIREFOX_BINARY=fennec
  - export JPM_ADB_PATH=/usr/local/android-sdk/platform-tools/adb

script:
  - jpm-mobile test -v --adb /usr/local/android-sdk/platform-tools/adb -b fennec

