language: android
android:
  components:
  - platform-tools
  - tools
  - android-19
  - sys-img-armeabi-v7a-android-19
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd /tmp
- mkdir sdcard
- mksdcard -l jetpackSdCard 1024M sdcard/jpmsdcard.img
- rm -f sdcard/jpmsdcard.img.lock
- echo no | android create avd --force -n jpm -t android-19 --abi armeabi-v7a
- emulator -avd jpm -sdcard sdcard/jpmsdcard.img -no-audio -gpu off -no-boot-anim -noskin &
- android-wait-for-emulator
before_script:
- git clone --depth 1 -b fixes https://github.com/ncalexan/jpm-mobile.git
- cd jpm-mobile
- npm link
- cd ..
- npm install -g get-firefox
- get-firefox -c -p android -t fennec.apk
- adb shell input keyevent 82 &
- adb install fennec.apk
- cd $TRAVIS_BUILD_DIR
- export JPM_FIREFOX_BINARY=fennec
- export JPM_ADB_PATH=/usr/local/android-sdk/platform-tools/adb
script:
- jpm-mobile test -v --adb $JPM_ADB_PATH -b $JPM_FIREFOX_BINARY
deploy:
  provider: npm
  email: martin@humanoids.be
  on:
    tags: true
  api_key:
    secure: DNgnzqrmCBaER+yEvGCAeRJLL9BeBjfvZC/K+gos/QUzQ6S/EaDjSGRJGBxarW0k5EbGL9LkrgBy3M3nXzHsLCDcS4ewvzKL4X6jH2qfIPvQc6fLu/lKy9yBrRfyaiG8fKVR+3Vm7YlZ940OCtiLkEf1Z+ezPY5TJdjKJEmjv2Q=
