language: android
android:
  components:
  - platform-tools
  - tools
  - android-19
  - sys-img-armeabi-v7a-android-19
env:
  global:
  - DISPLAY=:99.0
  - JPM_ADB_PATH=/usr/local/android-sdk/platform-tools/adb
  - JPM_FIREFOX_BINARY=nightly
  - TMP_DIR=/tmp
before_install:
- sh -e /etc/init.d/xvfb start
- echo no | android create avd --force -n jpm -t android-19 --abi armeabi-v7a --sdcard 1024M
- emulator -avd jpm -noaudio -no-skin &
before_script:
- npm install -g get-firefox
- git clone --depth 1 -b ncalexan-fixes https://github.com/freaktechnik/jpm-mobile.git $TMP_DIR/jpm-mobile
- cd $TMP_DIR/jpm-mobile
- npm link
- cd $TRAVIS_BUILD_DIR
- get-firefox -c -p android -t $TMP_DIR/fennec.apk
- android-wait-for-emulator
- adb install $TMP_DIR/fennec.apk
- adb shell input keyevent 82
script:
- jpm-mobile test -v --adb $JPM_ADB_PATH -b $JPM_FIREFOX_BINARY
deploy:
  provider: npm
  email: martin@humanoids.be
  on:
    tags: true
  api_key:
    secure: DNgnzqrmCBaER+yEvGCAeRJLL9BeBjfvZC/K+gos/QUzQ6S/EaDjSGRJGBxarW0k5EbGL9LkrgBy3M3nXzHsLCDcS4ewvzKL4X6jH2qfIPvQc6fLu/lKy9yBrRfyaiG8fKVR+3Vm7YlZ940OCtiLkEf1Z+ezPY5TJdjKJEmjv2Q=
